---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-prod"
spec:
  rules:
  - host: "jenkins{{ domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-service
          servicePort: jenkins-ui
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - "jenkins{{ domain }}"
    secretName: jenkins-cert # < cert-manager will store the created certificate in this sec
