- name: Wait for workers to become ready
  shell: |
    kubectl get nodes {{ hostvars[item]['ansible_facts']['nodename'] | lower }} -o json | jq -r '.status.conditions[] | select(.reason == "KubeletReady") | .type '
  register: result
  until: result.stdout.find("Ready") != -1
  retries: 60
  delay: 10
  with_items:
  - "{{ groups['workers'] }}"